baseURL = 'https://mariusandrian.github.io/'
languageCode = 'en-us'
title = "marius' dev log"
theme = 'PaperMod'

[params]
defaultTheme = "light"
disableThemeToggle = true
ShowBreadCrumbs = true

[params.homeInfoParams]
Title = "hello!"
Content = "My name is Marius, I'm a software engineer in Sydney currently specializing in C++. I have 4+ years experience in backend development in Kotlin and Go. This blog is to document my learnings from C++ and my projects. Feel free to reach out through <a href='mailto:marius.atj@gmail.com' target='_blank'>email</a> or linkedIn!"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/mariusandrian/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/mariusandrian"

[markup.goldmark.renderer]
unsafe= true