baseURL = 'https://mariusandrian.github.io/'
languageCode = 'en-us'
title = "marius' dev log"
theme = 'PaperMod'

[params]
ShowBreadCrumbs = true

[params.homeInfoParams]
Title = "hello!"
Content = "My name is Marius, I'm a software engineer in Sydney with 4+ years backend development experience. This blog is to document technical things I find intriguing and my side projects. Feel free to reach out through <a href='mailto:marius.atj@gmail.com' target='_blank'>email</a> or linkedIn!"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/mariusandrian/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/mariusandrian"

[markup.goldmark.renderer]
unsafe= true
